Label JSX template file added to src/components
nyc-cto/uswds pull request #6
Opened 2020-08-10 19:49 UTC by JohnAKASquib

## Description

This pull requests adds the .jsx template file for creating `<label>` components inside of _src/components/03-labels_. It follows the same structure as the `<button>` template file, so its returns an HTML `<label>` and has its attributes documented with JSDoc comments.

2020-08-11 17:48 UTC, MathewDavidov commented
Closes https://github.com/nyc-cto/USWDS-generator/issues/59

2020-08-13 13:54 UTC, mkcode commented on src/components/03-labels/label.jsx
> + *   }
Examples should call the function.

2020-08-13 13:55 UTC, mkcode commented on src/components/03-labels/label.jsx
> + * @returns {HTMLLabelElement} The JSX HTML Label
It doesn't return JSX. It does return an HTMLLabelElement

2020-08-13 13:55 UTC, mkcode requested changes
Few changes to improve the docs

2020-08-31 15:23 UTC, merged